# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Specify Vagrant box to use
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "https://atlas.hashicorp.com/ubuntu/trusty64"

  # Forward ports so we can access the web server hosting TicketSys
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Run provisioning scripts to update, install packages, etc.
  config.vm.provision "shell", inline: <<-SHELL
    sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password derp99'
    sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password derp99'
    sudo apt-get update
    sudo apt-get -y install lamp-server^
    sudo rm /var/www/html/index.html
    sudo apt-get -y install git
    sudo git clone https://github.com/Taurophylax/TicketSys.git /var/www/html
  SHELL
end
