Vagrant.configure("2") do |config|

  config.vm.box = "scotch/box"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.hostname = "scotchbox"
  #config.vm.synced_folder ".", "/var/www", :mount_options => ["dmode=777", "fmode=666"]
  config.vm.provision "shell", inline: <<-SHELL
    sudo git clone https://github.com/Taurophylax/TicketSys.git /var/www/public
    sudo service apache2 start
  SHELL

end
